# Generated by Django 5.1.7 on 2025-03-27 10:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
