# Generated by Django 5.1.7 on 2025-03-27 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapp', '0006_alter_score_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 10, 50, 6, 847144)),
        ),
    ]
